# Generated by Django 5.2.3 on 2025-07-24 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_ngoprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("total_campaigns", models.PositiveIntegerField(default=0)),
                ("total_donations", models.PositiveIntegerField(default=0)),
                ("total_food_donations", models.PositiveIntegerField(default=0)),
                ("total_food_requests", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="ngoprofile",
            old_name="registration_number",
            new_name="organization_name",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="ngo_name",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="registration_proof",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="service_areas",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="status",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="type_of_ngo",
        ),
        migrations.RemoveField(
            model_name="ngoprofile",
            name="website",
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                (
                    "food_type",
                    models.CharField(
                        choices=[("veg", "Vegetarian"), ("nonveg", "Non-Vegetarian")],
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit", models.CharField(default="kg", max_length=10)),
                ("pickup_address", models.TextField()),
                ("pickup_deadline", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        limit_choices_to={"role": "donor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="app.fooddonation",
                    ),
                ),
                (
                    "ngo",
                    models.ForeignKey(
                        limit_choices_to={"role": "ngo"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
