# Generated by Django 5.2.3 on 2025-07-25 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_systemstats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooddonation",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "ngo"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
