# Generated by Django 5.2.3 on 2025-07-25 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="fooddonation",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "ngo"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_food_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
